component:
  name: TaskManagerComponent
  type: service
  runtime: nodejs
  version: 1.0.0

environment:
  variables:
    PORT: 4000
    dbName: Task-management
    dbUrl: mongodb+srv://shagilhmx:Vit19-fna@mycluster.jmklzq4.mongodb.net/?retryWrites=true&w=majority&appName=MyCluster
    SALT_ROUNDS: 10
    JWT_SECRET: FDFLKNLIJO99409IT49J
    JWT_EXPIRE: 1d

dependencies:
    - name: express
      version: ^4.17.1
    - name: mongoose
      version: ^5.10.9
    - name: jsonwebtoken
      version: ^8.5.1
    - name: bcrypt
      version: ^5.0.0
    - name: cors
      version: ^2.8.5
    - name: dotenv
      version: ^8.2.0
    - name: nodemon
      version: ^2.0.6